version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4584:4566-4584'
      - '8080:8080'
    environment:
      - SERVICES=sqs,sns,s3
      - DATA_DIR=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '/tmp/localstack:/tmp/localstack'

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    env_file: development.env
    volumes:
      - './frontend:/app'
    depends_on:
      - localstack
      - postgres

  processing-file:
    build: ./processing-file
    env_file: development.env
    volumes:
      - './processing-file:/app'
    ports:
      - '3001:3000'
    depends_on:
      - localstack
      - redis

  save-record:
    build: ./save-record
    env_file: development.env
    volumes:
      - './save-record:/app'
    ports:
      - '3002:3000'
    depends_on:
      - localstack
