version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4584:4566-4584"
      - "8080:8080"
    environment:
      - SERVICES=sqs,sns,s3
      - DATA_DIR=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
