test:
  service: disk
  root: <%= Rails.root.join('tmp/storage') %>

development:
  service: S3
  access_key_id: '<%= ENV["AWS_ACCESS_KEY_ID"] %>'
  secret_access_key: '<%= ENV["AWS_SECRET_ACCESS_KEY"] %>'
  region: '<%= ENV["AWS_REGION"] %>'
  bucket: '<%= ENV["AWS_BUCKET"] %>'
  endpoint: '<%= ENV["AWS_ENDPOINT"] %>'
  force_path_style: true
